"""Service for managing component freshness policy configurations."""

from pathlib import Path
import yaml

from ..models.freshness import FreshnessPolicy
from ..api.env_vars import EnvVariable


class FreshnessService:
    """Service for applying freshness policies to components."""

    def update_env_vars(self, project_dir: Path, freshness_policy: FreshnessPolicy, asset_key: str | None = None) -> None:
        """
        Update .env file with freshness policy environment variables.

        Reads existing env vars from .env file, adds/updates freshness-related vars,
        and writes back to the file. This integrates with the existing env var management system.

        Args:
            project_dir: Path to the project root directory
            freshness_policy: Freshness policy configuration
            asset_key: Optional asset key for context in variable naming
        """
        env_file_path = project_dir / ".env"

        # Determine which env vars are needed
        env_vars_needed = {}

        if freshness_policy.maximum_lag_env_var:
            # Suggest relaxed dev value (4x the static value if available)
            dev_value = (freshness_policy.maximum_lag_minutes * 4) if freshness_policy.maximum_lag_minutes else 240
            env_vars_needed[freshness_policy.maximum_lag_env_var] = str(dev_value)

        if freshness_policy.cron_env_var:
            example_cron = freshness_policy.cron_schedule or "0 */6 * * *"
            env_vars_needed[freshness_policy.cron_env_var] = example_cron

        if not env_vars_needed:
            # No env vars to add
            return

        # Read existing env vars
        existing_vars = {}
        if env_file_path.exists():
            try:
                with open(env_file_path, 'r') as f:
                    for line in f:
                        line = line.strip()
                        # Skip empty lines and comments
                        if not line or line.startswith('#'):
                            continue

                        # Parse key=value
                        if '=' in line:
                            key, value = line.split('=', 1)
                            key = key.strip()
                            value = value.strip()

                            # Remove quotes if present
                            if (value.startswith('"') and value.endswith('"')) or \
                               (value.startswith("'") and value.endswith("'")):
                                value = value[1:-1]

                            existing_vars[key] = value
            except Exception as e:
                print(f"[Freshness Service] Warning: Failed to read existing .env file: {str(e)}")

        # Merge new env vars (only add if not already present)
        updated = False
        for key, default_value in env_vars_needed.items():
            if key not in existing_vars:
                existing_vars[key] = default_value
                updated = True
                print(f"[Freshness Service] Added env var: {key}={default_value}")

        # Write back to .env file if we added new vars
        if updated:
            try:
                with open(env_file_path, 'w') as f:
                    f.write("# Environment variables for Dagster project\n")
                    f.write("# Generated by Dagster Designer\n")
                    f.write("#\n")
                    f.write("# For Dagster+ deployments:\n")
                    f.write("# Set these values in the Dagster+ UI per deployment (prod/staging/branch)\n")
                    f.write("# See: https://docs.dagster.io/deployment/dagster-plus/management/environment-variables\n\n")

                    for key, value in existing_vars.items():
                        # Quote values that contain spaces or special characters
                        if ' ' in value or any(c in value for c in ['#', '$', '&', '|', ';']):
                            value = f'"{value}"'

                        f.write(f"{key}={value}\n")

                print(f"[Freshness Service] Updated .env file at {env_file_path}")

            except Exception as e:
                print(f"[Freshness Service] Error: Failed to write .env file: {str(e)}")

    def write_template_vars(self, component_dir: Path, freshness_policy: FreshnessPolicy, asset_key: str | None = None) -> None:
        """
        Write or update template_vars.py file with freshness policy function.

        Args:
            component_dir: Path to the component directory
            freshness_policy: Freshness policy configuration
            asset_key: Optional asset key for generating asset-specific env vars
        """
        template_vars_path = component_dir / "template_vars.py"

        # Generate freshness policy code
        freshness_code = freshness_policy.to_python_code(asset_key=asset_key)

        freshness_function = f'''
@dg.template_var
def component_freshness_policy():
    """Freshness policy for all assets in this component."""
    return {freshness_code}
'''

        if template_vars_path.exists():
            # Read existing content
            content = template_vars_path.read_text()

            # Check if freshness function already exists
            if "def component_freshness_policy(" in content:
                # Replace existing function
                import re
                # Match the entire function including decorator
                pattern = r'@dg\.template_var\s+def component_freshness_policy\(\)[^:]*:(?:[^\n]*\n(?:    [^\n]*\n)*)'
                content = re.sub(pattern, freshness_function.strip() + '\n', content, count=1)
            else:
                # Append new function
                if not content.endswith('\n'):
                    content += '\n'
                content += freshness_function

            template_vars_path.write_text(content)
        else:
            # Create new file with freshness function
            # Check if we need os import
            needs_os_import = freshness_policy.maximum_lag_env_var or freshness_policy.cron_env_var
            os_import = '\nimport os' if needs_os_import else ''

            header = f'''"""Template variables for this component."""

import dagster as dg{os_import}
'''
            template_vars_path.write_text(header + freshness_function)

        print(f"[Freshness Service] Updated template_vars.py with freshness policy")

    def update_defs_yaml(self, component_dir: Path, freshness_policy: FreshnessPolicy, asset_key: str | None = None) -> None:
        """
        Update defs.yaml to include freshness_policy in post_processing.

        Args:
            component_dir: Path to the component directory
            freshness_policy: Freshness policy configuration
            asset_key: Optional asset key for generating asset-specific env vars
        """
        defs_yaml_path = component_dir / "defs.yaml"
        if not defs_yaml_path.exists():
            print(f"[Freshness Service] defs.yaml not found at {defs_yaml_path}")
            return

        # Load existing defs.yaml
        with open(defs_yaml_path, 'r') as f:
            defs_data = yaml.safe_load(f) or {}

        # Check if freshness policy is active (enabled for backwards compat, or mode != none)
        is_active = freshness_policy.enabled or freshness_policy.mode != "none"

        if is_active:
            # Determine the freshness reference based on mode
            if freshness_policy.mode == "template" and freshness_policy.template_name:
                # Template mode: just reference the template name directly
                freshness_reference = freshness_policy.template_name
                print(f"[Freshness Service] Using template reference: {freshness_reference}")
            else:
                # Inline mode: write template_vars.py with freshness function and reference it
                self.write_template_vars(component_dir, freshness_policy, asset_key=asset_key)

                # Ensure template_vars_module is set in defs.yaml
                if "template_vars_module" not in defs_data:
                    defs_data["template_vars_module"] = ".template_vars"

                freshness_reference = "{{ component_freshness_policy }}"
                print(f"[Freshness Service] Using inline definition with template var")

            # Add or update post_processing
            if "post_processing" not in defs_data:
                defs_data["post_processing"] = {"assets": []}
            elif "assets" not in defs_data["post_processing"]:
                defs_data["post_processing"]["assets"] = []

            # Check if freshness policy post-processing already exists
            assets_list = defs_data["post_processing"]["assets"]
            freshness_entry_index = None

            for i, asset_entry in enumerate(assets_list):
                if asset_entry.get("target") == "*" and "freshness_policy" in asset_entry.get("attributes", {}):
                    freshness_entry_index = i
                    break

            # Create freshness policy post-processing entry
            freshness_entry = {
                "target": "*",
                "attributes": {
                    "freshness_policy": freshness_reference
                }
            }

            if freshness_entry_index is not None:
                # Update existing entry
                assets_list[freshness_entry_index] = freshness_entry
            else:
                # Add new entry
                assets_list.append(freshness_entry)

            print(f"[Freshness Service] Added freshness policy to defs.yaml")
        else:
            # Remove freshness policy from post_processing if it exists
            if "post_processing" in defs_data and "assets" in defs_data["post_processing"]:
                # Filter out freshness-related post_processing rules
                assets = defs_data["post_processing"]["assets"]
                filtered_assets = [
                    asset for asset in assets
                    if not (
                        asset.get("target") == "*" and
                        "freshness_policy" in asset.get("attributes", {})
                    )
                ]

                if filtered_assets:
                    defs_data["post_processing"]["assets"] = filtered_assets
                else:
                    # Remove post_processing entirely if empty
                    defs_data.pop("post_processing", None)

            print(f"[Freshness Service] Removed freshness policy from defs.yaml")

        # Write updated defs.yaml
        with open(defs_yaml_path, 'w') as f:
            yaml.dump(defs_data, f, default_flow_style=False, sort_keys=False)

    def apply_freshness_policy(
        self,
        component_dir: Path,
        freshness_policy: FreshnessPolicy,
        asset_key: str | None = None,
        project_dir: Path | None = None
    ) -> None:
        """
        Apply freshness policy configuration to a component.

        This updates defs.yaml with freshness_policy in post_processing
        and adds environment variables to .env if using environment variables.

        Args:
            component_dir: Path to the component directory
            freshness_policy: Freshness policy configuration
            asset_key: Optional asset key for generating asset-specific env vars
            project_dir: Optional project root directory for .env file updates
        """
        print(f"[Freshness Service] Applying freshness policy to {component_dir.name}")

        # Update defs.yaml
        self.update_defs_yaml(component_dir, freshness_policy, asset_key=asset_key)

        # Update .env file if using environment variables
        if project_dir and (freshness_policy.maximum_lag_env_var or freshness_policy.cron_env_var):
            self.update_env_vars(project_dir, freshness_policy, asset_key=asset_key)

        print(f"[Freshness Service] Freshness policy applied successfully")


# Singleton instance
freshness_service = FreshnessService()
