"""API endpoints for environment variable management."""

from pathlib import Path
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ..core.config import settings

router = APIRouter(prefix="/env", tags=["env"])


class EnvVariable(BaseModel):
    """Environment variable model."""
    key: str
    value: str
    is_sensitive: bool = False


class EnvVarsResponse(BaseModel):
    """Response model for environment variables."""
    variables: list[EnvVariable]


class EnvVarsUpdate(BaseModel):
    """Request model for updating environment variables."""
    variables: list[EnvVariable]


# List of keywords that indicate a sensitive variable
SENSITIVE_KEYWORDS = [
    "password", "secret", "key", "token", "api_key", "apikey",
    "auth", "credential", "private", "passphrase", "salt"
]


def is_sensitive_variable(key: str) -> bool:
    """Check if a variable key indicates sensitive data."""
    key_lower = key.lower()
    return any(keyword in key_lower for keyword in SENSITIVE_KEYWORDS)


@router.get("/{project_id}")
async def get_env_vars(project_id: str) -> EnvVarsResponse:
    """
    Get environment variables for a project.

    Args:
        project_id: Project ID

    Returns:
        List of environment variables
    """
    # Get project path
    project_file = (settings.projects_dir / f"{project_id}.json").resolve()
    if not project_file.exists():
        raise HTTPException(status_code=404, detail=f"Project {project_id} not found")

    # Read project metadata to get directory name
    import json
    with open(project_file, 'r') as f:
        project_data = json.load(f)

    directory_name = project_data.get("directory_name", project_id)
    project_path = (settings.projects_dir / directory_name).resolve()

    if not project_path.exists():
        raise HTTPException(status_code=404, detail=f"Project directory not found")

    # Read .env file
    env_file = project_path / ".env"
    variables = []

    if env_file.exists():
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    # Skip empty lines and comments
                    if not line or line.startswith('#'):
                        continue

                    # Parse key=value
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip()

                        # Remove quotes if present
                        if (value.startswith('"') and value.endswith('"')) or \
                           (value.startswith("'") and value.endswith("'")):
                            value = value[1:-1]

                        variables.append(EnvVariable(
                            key=key,
                            value=value,
                            is_sensitive=is_sensitive_variable(key)
                        ))
        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Failed to read .env file: {str(e)}"
            )

    return EnvVarsResponse(variables=variables)


@router.put("/{project_id}")
async def update_env_vars(project_id: str, update: EnvVarsUpdate):
    """
    Update environment variables for a project.

    Args:
        project_id: Project ID
        update: Updated environment variables

    Returns:
        Success message
    """
    # Get project path
    project_file = (settings.projects_dir / f"{project_id}.json").resolve()
    if not project_file.exists():
        raise HTTPException(status_code=404, detail=f"Project {project_id} not found")

    # Read project metadata to get directory name
    import json
    with open(project_file, 'r') as f:
        project_data = json.load(f)

    directory_name = project_data.get("directory_name", project_id)
    project_path = (settings.projects_dir / directory_name).resolve()

    if not project_path.exists():
        raise HTTPException(status_code=404, detail=f"Project directory not found")

    # Write .env file
    env_file = project_path / ".env"

    try:
        with open(env_file, 'w') as f:
            f.write("# Environment variables for Dagster project\n")
            f.write("# Generated by Dagster Designer\n\n")

            for var in update.variables:
                # Quote values that contain spaces or special characters
                value = var.value
                if ' ' in value or any(c in value for c in ['#', '$', '&', '|', ';']):
                    value = f'"{value}"'

                f.write(f"{var.key}={value}\n")

        return {"message": "Environment variables updated successfully"}

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to write .env file: {str(e)}"
        )
